before_script:
  - cp tests/ftests/config.php.dist tests/ftests/config.php
  #This version is supported by php 5.4
  - curl -o ./phpunit https://phar.phpunit.de/phpunit-4.8.9.phar
  - chmod +x ./phpunit

php5.3:
  image: dalenys/php:5.3
  script:
    - php --version
    - ./phpunit

php5.4:
  image: dalenys/php:5.4
  script:
    - php --version
    - ./phpunit

php5.5:
  image: dalenys/php:5.5
  script:
    - php --version
    - ./phpunit

php5.6:
  image: dalenys/php:5.6
  script:
    - php --version
    - ./phpunit

php7.0:
  image: dalenys/php:7.0
  script:
    - php --version
    - ./phpunit

hhvm:
  image: dalenys/php:hhvm
  script:
    - php --version
    - ./phpunit
