before_script:
  - cp tests/ftests/config.php.dist tests/ftests/config.php
  #This version is supported by php 5.4
  - curl -o ./phpunit https://phar.phpunit.de/phpunit-4.8.9.phar
  - chmod +x ./phpunit

  
php5.4:
  script:
    - php-choose-version 5.4 && php --version
    - ./phpunit

php5.5:
  script:
    - php-choose-version 5.5 && php --version
    - ./phpunit

php5.6:
  script:
    - php-choose-version 5.6 && php --version
    - ./phpunit
