language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    # Actually, the phpunit vesion of 5.2 vm is not compatible with testsuite parameters
    - php: 5.2
install: cp tests/ftests/config.php.dist tests/ftests/config.php
script: phpunit --coverage-text --testsuite utests