language: php

php:
  # - 5.2 Removed because travis doesn't seems to support anymore this version
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install: cp tests/ftests/config.php.dist tests/ftests/config.php
script: phpunit --coverage-text tests/utests